.TH WXMACMOLPLT 1 "24 January 2007" "Version 6.2.1" "wxMacMolPlt User Manual"
.SH NAME
wxMacMolPlt \- insert basic description here
.SH SYNOPSIS
.B wxmacmolplt
[\-\-optional-command]
.SH DESCRIPTION
Insert description of wxMacMolPlt and where to go for additional documentation.
.SH OPTIONS
wxMacMolPlt accepts the following options:

Insert command line options
.SH FILES
Insert list of important files.
.SH ENVIRONMENT
Insert list of environment variables that are checked.  Remove section if none.
.SH BUGS
Insert list of known bugs and how to report new ones.
.SH AUTHOR
Brett Bode <brett@scl.ameslab.gov>
