.TH WXMACMOLPLT 1 "27 January 2007" "Version 6.2.1" "wxMacMolPlt User Manual"
.SH NAME
wxMacMolPlt \- molecular visualization program
.SH SYNOPSIS
.B wxmacmolplt [options] [input file]
.SH DESCRIPTION
wxMacMolPlt is designed to display the input and output of the GAMESS quantum
chemistry package.  It produces animations and/or publication quality output
from a variety of input file formats.
.nh
.nf
.PP
Complete documentation is usually installed at
/usr/share/wxmacmolplt/MacMolPlt_Manual.html
.PP
More information may be found at
http://www.scl.ameslab.gov/~brett/MacMolPlt/
.fi
.hy
.SH OPTIONS
wxMacMolPlt accepts the following options:
.TP
\fB\-h\fR, \fB\-\-help\fR
displays help on the command line parameters
.TP
\fB\-v\fR, \fB\-\-version\fR
print version
.SH FILES
Insert list of important files.
.SH BUGS
wxMacMolPlt is still undergoing development, and there are probably still
several bugs.  If you find one, please e-mail the author with a description of
the bug and instructions for reproducing it.
.SH AUTHOR
Brett Bode <brett@scl.ameslab.gov>
