/////////////////////////////////////////////////////////////////////////////
// Name:        aboutwxmacmolplt.h
// Purpose:     
// Author:      Brett Bode
// Modified by: 
// Created:     Tue 23 May 13:01:58 2006
// Copyright:   (c) 2006 Iowa State University
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks, Tue 23 May 13:01:58 2006

#ifndef _ABOUTWXMACMOLPLT_H_
#define _ABOUTWXMACMOLPLT_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "aboutwxmacmolplt.h"
#endif

/*!
 * Includes
 */

////@begin includes
#if wxCHECK_VERSION(2, 8, 0)
#include "wx/hyperlink.h"
#endif
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10053
#define ID_HYPERLINKCTRL2 10258
#define ID_HYPERLINKCTRL1 10257
#define ID_HYPERLINKCTRL3 10259
#define SYMBOL_ABOUTWXMACMOLPLT_STYLE wxDEFAULT_DIALOG_STYLE
#define SYMBOL_ABOUTWXMACMOLPLT_TITLE _("About wxMacMolPlt")
#define SYMBOL_ABOUTWXMACMOLPLT_IDNAME ID_DIALOG
#define SYMBOL_ABOUTWXMACMOLPLT_SIZE wxSize(400, 300)
#define SYMBOL_ABOUTWXMACMOLPLT_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/**
 * The about dialog. Just a simple modal dialog.
 */

class AboutwxMacMolPlt: public wxDialog
{    
	DECLARE_DYNAMIC_CLASS( AboutwxMacMolPlt )
	DECLARE_EVENT_TABLE()

	public:
		/// Constructors
		AboutwxMacMolPlt( );
		AboutwxMacMolPlt( wxWindow* parent, wxWindowID id = SYMBOL_ABOUTWXMACMOLPLT_IDNAME, const wxString& caption = SYMBOL_ABOUTWXMACMOLPLT_TITLE, const wxPoint& pos = SYMBOL_ABOUTWXMACMOLPLT_POSITION, const wxSize& size = SYMBOL_ABOUTWXMACMOLPLT_SIZE, long style = SYMBOL_ABOUTWXMACMOLPLT_STYLE );

		/// Creation
		bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ABOUTWXMACMOLPLT_IDNAME, const wxString& caption = SYMBOL_ABOUTWXMACMOLPLT_TITLE, const wxPoint& pos = SYMBOL_ABOUTWXMACMOLPLT_POSITION, const wxSize& size = SYMBOL_ABOUTWXMACMOLPLT_SIZE, long style = SYMBOL_ABOUTWXMACMOLPLT_STYLE );

		/// Creates the controls and sizers
		void CreateControls();

////@begin AboutwxMacMolPlt event handler declarations

////@end AboutwxMacMolPlt event handler declarations

////@begin AboutwxMacMolPlt member function declarations

		/// Retrieves bitmap resources
		wxBitmap GetBitmapResource( const wxString& name );

		/// Retrieves icon resources
		wxIcon GetIconResource( const wxString& name );
////@end AboutwxMacMolPlt member function declarations

		/// Should we show tooltips?
		static bool ShowToolTips();

////@begin AboutwxMacMolPlt member variables
		wxStaticText* mVersionText;
////@end AboutwxMacMolPlt member variables
};

#endif
// _ABOUTWXMACMOLPLT_H_
