/////////////////////////////////////////////////////////////////////////////
// Name:        exportoptionsdialog.h
// Purpose:     
// Author:      Brett Bode
// Modified by: 
// Created:     Thu 11 May 2006 02:46:50 PM CDT
// RCS-ID:      
// Copyright:   (c) 2006 Iowa State University
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Thu 11 May 2006 02:46:50 PM CDT

#ifndef _EXPORTOPTIONSDIALOG_H_
#define _EXPORTOPTIONSDIALOG_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "exportoptionsdialog.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_EXPORTOPTIONSDIALOG 10044
#define SYMBOL_EXPORTOPTIONSDIALOG_STYLE wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxSYSTEM_MENU|wxSTAY_ON_TOP|wxDIALOG_MODAL
#define SYMBOL_EXPORTOPTIONSDIALOG_TITLE _("Export Options")
#define SYMBOL_EXPORTOPTIONSDIALOG_IDNAME ID_EXPORTOPTIONSDIALOG
#define SYMBOL_EXPORTOPTIONSDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_EXPORTOPTIONSDIALOG_POSITION wxDefaultPosition
#define ID_FILE_TYPE_CHOICE 10045
#define ID_SCREEN_RES_RADIOBUTTON 10046
#define ID_RES_CHOICE 10047
#define ID_CUSTOM_RES_RADIOBUTTON 10048
#define ID_RES_WIDTH_TEXT 10049
#define ID_RES_HEIGHT_TEXT 10050
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * ExportOptionsDialog class declaration
 */

class ExportOptionsDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ExportOptionsDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ExportOptionsDialog( );
    ExportOptionsDialog( wxWindow* parent, wxWindowID id = SYMBOL_EXPORTOPTIONSDIALOG_IDNAME, const wxString& caption = SYMBOL_EXPORTOPTIONSDIALOG_TITLE, const wxPoint& pos = SYMBOL_EXPORTOPTIONSDIALOG_POSITION, const wxSize& size = SYMBOL_EXPORTOPTIONSDIALOG_SIZE, long style = SYMBOL_EXPORTOPTIONSDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_EXPORTOPTIONSDIALOG_IDNAME, const wxString& caption = SYMBOL_EXPORTOPTIONSDIALOG_TITLE, const wxPoint& pos = SYMBOL_EXPORTOPTIONSDIALOG_POSITION, const wxSize& size = SYMBOL_EXPORTOPTIONSDIALOG_SIZE, long style = SYMBOL_EXPORTOPTIONSDIALOG_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin ExportOptionsDialog event handler declarations

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_FILE_TYPE_CHOICE
    void OnFileTypeChoiceSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_RADIOBUTTON_SELECTED event handler for ID_SCREEN_RES_RADIOBUTTON
    void OnScreenResRadiobuttonSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_RES_CHOICE
    void OnResChoiceSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_RADIOBUTTON_SELECTED event handler for ID_CUSTOM_RES_RADIOBUTTON
    void OnCustomResRadiobuttonSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_RES_WIDTH_TEXT
    void OnResWidthTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_RES_HEIGHT_TEXT
    void OnResHeightTextUpdated( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end ExportOptionsDialog event handler declarations


    int getWidth() const { return width ; }
    int getHeight() const { return height ; }
    wxString getFiletype() const { return filetype ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );


    /// Should we show tooltips?
    static bool ShowToolTips();

private:
    long width;
    long height;
    double H2Wratio;
    wxString filetype;

    wxChoice        *fileTypeChoice;
    wxChoice        *resChoice;
    wxStaticText    *txt0;
    wxStaticText    *txt1;
    wxStaticText    *txt2;
    wxStaticText    *txt3;
    wxTextCtrl      *resWidthText;
    wxTextCtrl      *resHeightText;
    wxTextValidator  widthValidator;
    wxTextValidator  heightValidator;
    wxButton        *okButton;
};

#endif
    // _EXPORTOPTIONSDIALOG_H_
