/////////////////////////////////////////////////////////////////////////////
// Name:        exportoptions.h
// Purpose:     
// Author:      Brett Bode
// Modified by: 
// Created:     Thu 11 May 2006 02:22:56 PM CDT
// RCS-ID:      
// Copyright:   (c) 2006 Iowa State University
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Thu 11 May 2006 02:22:56 PM CDT

#ifndef _EXPORTOPTIONS_H_
#define _EXPORTOPTIONS_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "exportoptions.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_EXPORTOPTIONS 10044
#define SYMBOL_EXPORTOPTIONS_STYLE wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxSYSTEM_MENU|wxSTAY_ON_TOP|wxDIALOG_MODAL
#define SYMBOL_EXPORTOPTIONS_TITLE _("Export Options")
#define SYMBOL_EXPORTOPTIONS_IDNAME ID_EXPORTOPTIONS
#define SYMBOL_EXPORTOPTIONS_SIZE wxSize(400, 300)
#define SYMBOL_EXPORTOPTIONS_POSITION wxDefaultPosition
#define ID_FILE_TYPE_CHOICE 10045
#define ID_SCREEN_RES_RADIOBUTTON 10046
#define ID_RES_CHOICE 10047
#define ID_CUSTOM_RES_RADIOBUTTON 10048
#define ID_RES_WIDTH_TEXT 10049
#define ID_RES_HEIGHT_TEXT 10050
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * ExportOptions class declaration
 */

class ExportOptions: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ExportOptions )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ExportOptions( );
    ExportOptions( wxWindow* parent, wxWindowID id = SYMBOL_EXPORTOPTIONS_IDNAME, const wxString& caption = SYMBOL_EXPORTOPTIONS_TITLE, const wxPoint& pos = SYMBOL_EXPORTOPTIONS_POSITION, const wxSize& size = SYMBOL_EXPORTOPTIONS_SIZE, long style = SYMBOL_EXPORTOPTIONS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_EXPORTOPTIONS_IDNAME, const wxString& caption = SYMBOL_EXPORTOPTIONS_TITLE, const wxPoint& pos = SYMBOL_EXPORTOPTIONS_POSITION, const wxSize& size = SYMBOL_EXPORTOPTIONS_SIZE, long style = SYMBOL_EXPORTOPTIONS_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin ExportOptions event handler declarations

////@end ExportOptions event handler declarations

////@begin ExportOptions member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ExportOptions member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ExportOptions member variables
////@end ExportOptions member variables
};

#endif
    // _EXPORTOPTIONS_H_
