/////////////////////////////////////////////////////////////////////////////
// Name:        printoptions.h
// Purpose:     
// Author:      Brett Bode
// Modified by: 
// Created:     Tue 16 May 11:20:20 2006
// RCS-ID:      
// Copyright:   (c) 2006 Iowa State University
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Tue 16 May 11:20:20 2006

#ifndef _PRINTOPTIONS_H_
#define _PRINTOPTIONS_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "printoptions.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MYDIALOG1 10046
#define SYMBOL_PRINTOPTIONS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_PRINTOPTIONS_TITLE _("Print Options")
#define SYMBOL_PRINTOPTIONS_IDNAME ID_MYDIALOG1
#define SYMBOL_PRINTOPTIONS_SIZE wxSize(400, 300)
#define SYMBOL_PRINTOPTIONS_POSITION wxDefaultPosition
#define ID_CHECKBOX 10048
#define ID_CHECKBOX1 10050
#define ID_CHECKBOX2 10052
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * PrintOptions class declaration
 */

class PrintOptions: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( PrintOptions )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    PrintOptions( );
    PrintOptions( MolDisplayWin* parent, wxWindowID id = SYMBOL_PRINTOPTIONS_IDNAME, const wxString& caption = SYMBOL_PRINTOPTIONS_TITLE, const wxPoint& pos = SYMBOL_PRINTOPTIONS_POSITION, const wxSize& size = SYMBOL_PRINTOPTIONS_SIZE, long style = SYMBOL_PRINTOPTIONS_STYLE );

    /// Creation
    bool Create( MolDisplayWin* parent, wxWindowID id = SYMBOL_PRINTOPTIONS_IDNAME, const wxString& caption = SYMBOL_PRINTOPTIONS_TITLE, const wxPoint& pos = SYMBOL_PRINTOPTIONS_POSITION, const wxSize& size = SYMBOL_PRINTOPTIONS_SIZE, long style = SYMBOL_PRINTOPTIONS_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin PrintOptions event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

////@end PrintOptions event handler declarations

////@begin PrintOptions member function declarations

    MolDisplayWin * GetParent() const { return Parent ; }
    void SetParent(MolDisplayWin * value) { Parent = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end PrintOptions member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin PrintOptions member variables
    wxCheckBox* FrameCheck;
    wxCheckBox* CenterCheck;
    wxCheckBox* MaxCheck;
    MolDisplayWin * Parent;
////@end PrintOptions member variables
};

#endif
    // _PRINTOPTIONS_H_
